coverage:
  acceptable: 60%
  paths:
    - ../ext/lcov.info
comment:
  if: is_pull_request
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
