coverage:
  paths:
    - ../lcov.info
  acceptable: current >= 60%
testExecutionTime:
  acceptable: current <= 5min && diff < 5min
comment:
  if: is_pull_request
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
